### PR TITLE
Update Dockerfile to include `pyyaml`

### PR DESCRIPTION
**Pull request by jkozdon**
This permits the use yaml files for cmake-format

### CODE REVIEW

**Comment by puneetmatharu** [comment]
Hello! Apologies for the delay in my reply.

I've had a look at the change and I'm not sure it is necessary. The [documentation for `cmakelang`](https://cmake-format.readthedocs.io/en/latest/installation.html) states

```text
If you wish to use a configuration file in YAML format you’ll want to install with the optional YAML feature, e.g.:

pip install cmakelang[YAML]

or manually install pyyaml. 
```

In the same line that you have edited, I install `cmakelang` with the `pip` command:

```bash
pip install "cmakelang[YAML]==0.6.13"
```

Could you possibly explain why I would still need to run `pip install pyyaml` on top of that?

**Comment by ChengjieLi28** [comment]
Hi, @puneetmatharu . I met an issue about yaml support also.
When I use this action:
```
- name: cmake-format
  uses: PuneetMatharu/cmake-format-lint-action@v1.0.0
  with:
    args: --config-files .cmake-format.yaml --check
```
I met this error:
image

May I ask that does this PR fix this issue?

**Comment by ChengjieLi28** [comment]
Update: When I uprade action to ``v1.0.2``, the error above gone. So I think maybe updating README for better use would be good. :)

**Comment by puneetmatharu** [comment]
@ChengjieLi28 thank you for the suggestion; I have updated the README

@jkozdon there has been no activity on this PR in months and I don't see why the change is needed so I'm going to close it.

**Comment by jkozdon** [comment]
@puneetmatharu Sorry I missed this.

I don't know why this was needed. I was running into a problem on a self-hosted running, and this resolved the problem.

I am unable to reproduce the issue on a public runner so maybe it is a problem with the system I was using. (Or I just fat fingered something else when setting things up the first time.)

**Pull request closed without merging**
